version: '3.7'

services:
  couchdb:
    image: 'apache/couchdb:3'
    environment: # first time username and password values
      - 'COUCHDB_USER=admin'
      - 'COUCHDB_PASSWORD=password'
    ports:
      - '5984'
  pouchdb:
    image: 'ghcr.io/retrodaredevil/pouchdb-server:edge-4.2.0'
    command: --config /app/config.json
    volumes:
      - './pouchdb-config.json:/app/config.json:ro'
    ports:
      - '5984'

